name: Generate Snake

# Run every 6 hours or manually
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# Set permissions so the bot can push
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Generate the snake GIF/SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Kaif-Nazir
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show git status (optional, useful for debugging)
      - run: git status

      # Push the generated files to a separate branch called 'output'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # Deploy to GitHub Pages (optional)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
